name: sharek
version: 1.0.3+3
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.19.3 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  animations: ^2.0.7
  app_settings: ^4.2.0
  appinio_video_player: ^1.2.1
  audio_waveforms: ^1.0.4
  background_downloader: any
  bot_toast: ^4.0.3
  bubble: ^1.2.1
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.6.0
  connectivity_plus: ^3.0.3
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  dots_indicator: ^2.1.0
  dotted_border: null
  encrypt: ^5.0.1
  file_picker: ^5.2.2
  firebase_auth: ^4.1.1
  firebase_core: ^2.10.0
  firebase_dynamic_links: ^5.0.6
  firebase_messaging: ^14.4.1
  firebase_storage: ^11.0.4

  flutter:
    sdk: flutter
  flutter_link_previewer: ^3.2.0
  flutter_local_notifications: ^8.2.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.2.19
  flutter_slidable: ^3.0.0
  flutter_svg: ^2.0.4
  freezed_annotation: ^2.2.0
  geolocator: ^9.0.2
  get: 4.6.5
  get_storage: ^2.1.1
  iconsax: ^0.0.8
  image_picker: ^0.8.7+1
  image_pickers: ^2.0.1
  insta_image_viewer: ^1.0.2
  internet_connection_checker: ^1.0.0+1
  intl: any
  leak_tracker: ^2.0.1
  permission_handler: ^10.2.0
  pinput: ^2.2.31
  pretty_dio_logger: ^1.3.1
  provider: ^6.0.5
  responsive_framework: ^0.2.0
  round_spot: ^0.5.0
  sentry_flutter: ^7.7.0
  sentry_logging: ^7.7.0
  shared_preferences: ^2.1.0
  shimmer: ^2.0.0
  supercharged: ^2.1.1
  timeago: any
  url_launcher: ^6.1.11
  video_thumbnail: ^0.5.3
  visibility_detector: ^0.4.0+2
  workmanager: ^0.5.1

dev_dependencies:
  build_runner: any
  flutter_lints: 2.0.1
  flutter_test:
    sdk: flutter
  freezed: any
  icons_launcher: ^2.1.0

icons_launcher:
  image_path: "assets/images/logo.png"
  adaptive_background_color: "#ffffff"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Tajawal
      fonts:
        - asset: assets/fonts/Tajawal_Light.ttf
          weight: 300
        - asset: assets/fonts/Tajawal_Regular.ttf
          weight: 400
        - asset: assets/fonts/Tajawal_Medium.ttf
          weight: 500
        - asset: assets/fonts/Tajawal_Bold.ttf
          weight: 700
    - family: SuiizIcons
      fonts:
        - asset: assets/fonts/SuiizIcons.ttf

flutter_icons:
  android: "launcher_icon"
  ios: true

flutter_app_name:
  name: "Sharek "
