// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCktsSOhlnRgtvPaCDtB4IKTrLbq006RnI',
    appId: '1:877028796126:web:2206674842a2ee46c0044f',
    messagingSenderId: '877028796126',
    projectId: 'sharek-twinkle',
    authDomain: 'sharek-twinkle.firebaseapp.com',
    storageBucket: 'sharek-twinkle.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3x--u8Jd3Qxiem45y7Awtdd78G4mp0TI',
    appId: '1:877028796126:android:0c05e4982dd2d05dc0044f',
    messagingSenderId: '877028796126',
    projectId: 'sharek-twinkle',
    storageBucket: 'sharek-twinkle.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMomXj_3ghMKi2qrj3zs900G1Tb6YnNfo',
    appId: '1:877028796126:ios:fd70f0f7bf16f8b4c0044f',
    messagingSenderId: '877028796126',
    projectId: 'sharek-twinkle',
    storageBucket: 'sharek-twinkle.appspot.com',
    iosClientId: '877028796126-19ocg3933itrplagpdhalbfpfif61mf4.apps.googleusercontent.com',
    iosBundleId: 'com.elmarakby.sharek',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMomXj_3ghMKi2qrj3zs900G1Tb6YnNfo',
    appId: '1:877028796126:ios:fd70f0f7bf16f8b4c0044f',
    messagingSenderId: '877028796126',
    projectId: 'sharek-twinkle',
    storageBucket: 'sharek-twinkle.appspot.com',
    iosClientId: '877028796126-19ocg3933itrplagpdhalbfpfif61mf4.apps.googleusercontent.com',
    iosBundleId: 'com.elmarakby.sharek',
  );
}
